// Generated by the C# M2TypesGenerator: modify at your own risk!
// ReSharper disable InconsistentNaming
// ReSharper disable SuggestVarOrType_SimpleTypes
// ReSharper disable SuggestVarOrType_Elsewhere
#pragma warning disable 1591
#nullable enable
namespace com.strumenta.starlasu;
using global::LionWeb.Core;
using global::LionWeb.Core.M2;
using global::LionWeb.Core.M3;
using global::LionWeb.Core.Notification;
using global::LionWeb.Core.Utilities;
using global::LionWeb.Core.VersionSpecific.V2023_1;
using global::System;
using global::System.Collections.Generic;
using global::System.Diagnostics.CodeAnalysis;
using Strumenta.Sharplasu.Model;
using Strumenta.Sharplasu.Parsing;
using System.Linq;
using System.Text.Json.Serialization;
using System.Xml.Serialization;

/// <summary>
/// LionWeb primitive <c>TokensList</c>: behaves as <see cref="List{KolasuToken}"/> so
/// <c>ParsingResult.Tokens</c> can be used directly (no nested <c>.Tokens</c>).
/// </summary>
public class TokensList : List<KolasuToken>
{
    public TokensList()
    {
    }

    public TokensList(IEnumerable<KolasuToken> tokens)
        : base(tokens)
    {
    }
}

[LionCoreLanguage(Key = "com_strumenta_starlasu", Version = "1")]
public partial class StarLasuLanguage : LanguageBase<IStarLasuFactory>
{
	public static readonly StarLasuLanguage Instance = new Lazy<StarLasuLanguage>(() => new("com-strumenta-StarLasu")).Value;
	public StarLasuLanguage(string id) : base(id, LionWebVersions.v2023_1)
	{
		_aSTNode = new(() => new ConceptBase<StarLasuLanguage>("com-strumenta-StarLasu-ASTNode-id", this) { Key = "com_strumenta_starlasu-ASTNode-key", Name = "ASTNode", Abstract = false, Partition = false, FeaturesLazy = new(() => [ASTNode_originalNode, ASTNode_position, ASTNode_transpiledNodes]) });
		_aSTNode_originalNode = new(() => new ReferenceBase<StarLasuLanguage>("com-strumenta-StarLasu-ASTNode-originalNode-id", ASTNode, this) { Key = "com_strumenta_starlasu-ASTNode-originalNode-key", Name = "originalNode", Optional = true, Multiple = false, Type = ASTNode });
		_aSTNode_position = new(() => new PropertyBase<StarLasuLanguage>("com-strumenta-StarLasu-ASTNode-position-id", ASTNode, this) { Key = "com_strumenta_starlasu-ASTNode-position-key", Name = "position", Optional = true, Type = Position });
		_aSTNode_transpiledNodes = new(() => new ReferenceBase<StarLasuLanguage>("com-strumenta-StarLasu-ASTNode-transpiledNodes-id", ASTNode, this) { Key = "com_strumenta_starlasu-ASTNode-transpiledNodes-key", Name = "transpiledNodes", Optional = true, Multiple = true, Type = ASTNode });
		_behaviorDeclaration = new(() => new InterfaceBase<StarLasuLanguage>("com-strumenta-StarLasu-BehaviorDeclaration-id", this) { Key = "com_strumenta_starlasu-BehaviorDeclaration-key", Name = "BehaviorDeclaration", ExtendsLazy = new(() => [CommonElement]) });
		_char = new(() => new PrimitiveTypeBase<StarLasuLanguage>("com-strumenta-StarLasu-Char-id", this) { Key = "com_strumenta_starlasu-Char-key", Name = "Char" });
		_commonElement = new(() => new InterfaceBase<StarLasuLanguage>("com-strumenta-StarLasu-CommonElement-id", this) { Key = "com_strumenta_starlasu-CommonElement-key", Name = "CommonElement" });
		_documentation = new(() => new InterfaceBase<StarLasuLanguage>("com-strumenta-StarLasu-Documentation-id", this) { Key = "com_strumenta_starlasu-Documentation-key", Name = "Documentation", ExtendsLazy = new(() => [CommonElement]) });
		_entityDeclaration = new(() => new InterfaceBase<StarLasuLanguage>("com-strumenta-StarLasu-EntityDeclaration-id", this) { Key = "com_strumenta_starlasu-EntityDeclaration-key", Name = "EntityDeclaration", ExtendsLazy = new(() => [CommonElement]) });
		_entityGroupDeclaration = new(() => new InterfaceBase<StarLasuLanguage>("com-strumenta-StarLasu-EntityGroupDeclaration-id", this) { Key = "com_strumenta_starlasu-EntityGroupDeclaration-key", Name = "EntityGroupDeclaration", ExtendsLazy = new(() => [CommonElement]) });
		_expression = new(() => new InterfaceBase<StarLasuLanguage>("com-strumenta-StarLasu-Expression-id", this) { Key = "com_strumenta_starlasu-Expression-key", Name = "Expression", ExtendsLazy = new(() => [CommonElement]) });
		_issue = new(() => new ConceptBase<StarLasuLanguage>("com-strumenta-StarLasu-Issue-id", this) { Key = "com_strumenta_starlasu-Issue-key", Name = "Issue", Abstract = false, Partition = false, FeaturesLazy = new(() => [Issue_message, Issue_position, Issue_severity, Issue_type]) });
		_issue_message = new(() => new PropertyBase<StarLasuLanguage>("com-strumenta-StarLasu-Issue-message-id", Issue, this) { Key = "com_strumenta_starlasu-Issue-message-key", Name = "message", Optional = false, Type = _builtIns.String });
		_issue_position = new(() => new PropertyBase<StarLasuLanguage>("com-strumenta-StarLasu-Issue-position-id", Issue, this) { Key = "com_strumenta_starlasu-Issue-position-key", Name = "position", Optional = true, Type = Position });
		_issue_severity = new(() => new PropertyBase<StarLasuLanguage>("com-strumenta-StarLasu-Issue-severity-id", Issue, this) { Key = "com_strumenta_starlasu-Issue-severity-key", Name = "severity", Optional = false, Type = IssueSeverity });
		_issue_type = new(() => new PropertyBase<StarLasuLanguage>("com-strumenta-StarLasu-Issue-type-id", Issue, this) { Key = "com_strumenta_starlasu-Issue-type-key", Name = "type", Optional = false, Type = IssueType });
		_issueSeverity = new(() => new EnumerationBase<StarLasuLanguage>("com-strumenta-StarLasu_IssueSeverity", this) { Key = "IssueSeverity", Name = "IssueSeverity", LiteralsLazy = new(() => [IssueSeverity_ERROR, IssueSeverity_INFO, IssueSeverity_WARNING]) });
		_issueSeverity_ERROR = new(() => new EnumerationLiteralBase<StarLasuLanguage>("com-strumenta-StarLasu_IssueSeverity-ERROR", IssueSeverity, this) { Key = "IssueSeverity-ERROR", Name = "ERROR" });
		_issueSeverity_INFO = new(() => new EnumerationLiteralBase<StarLasuLanguage>("com-strumenta-StarLasu_IssueSeverity-INFO", IssueSeverity, this) { Key = "IssueSeverity-INFO", Name = "INFO" });
		_issueSeverity_WARNING = new(() => new EnumerationLiteralBase<StarLasuLanguage>("com-strumenta-StarLasu_IssueSeverity-WARNING", IssueSeverity, this) { Key = "IssueSeverity-WARNING", Name = "WARNING" });
		_issueType = new(() => new EnumerationBase<StarLasuLanguage>("com-strumenta-StarLasu_IssueType", this) { Key = "IssueType", Name = "IssueType", LiteralsLazy = new(() => [IssueType_LEXICAL, IssueType_SEMANTIC, IssueType_SYNTACTIC, IssueType_TRANSLATION]) });
		_issueType_LEXICAL = new(() => new EnumerationLiteralBase<StarLasuLanguage>("com-strumenta-StarLasu_IssueType-LEXICAL", IssueType, this) { Key = "IssueType-LEXICAL", Name = "LEXICAL" });
		_issueType_SEMANTIC = new(() => new EnumerationLiteralBase<StarLasuLanguage>("com-strumenta-StarLasu_IssueType-SEMANTIC", IssueType, this) { Key = "IssueType-SEMANTIC", Name = "SEMANTIC" });
		_issueType_SYNTACTIC = new(() => new EnumerationLiteralBase<StarLasuLanguage>("com-strumenta-StarLasu_IssueType-SYNTACTIC", IssueType, this) { Key = "IssueType-SYNTACTIC", Name = "SYNTACTIC" });
		_issueType_TRANSLATION = new(() => new EnumerationLiteralBase<StarLasuLanguage>("com-strumenta-StarLasu_IssueType-TRANSLATION", IssueType, this) { Key = "IssueType-TRANSLATION", Name = "TRANSLATION" });
		_parameter = new(() => new InterfaceBase<StarLasuLanguage>("com-strumenta-StarLasu-Parameter-id", this) { Key = "com_strumenta_starlasu-Parameter-key", Name = "Parameter", ExtendsLazy = new(() => [CommonElement]) });
		_parsingResult = new(() => new ConceptBase<StarLasuLanguage>("com-strumenta-StarLasu-ParsingResult-id", this) { Key = "com_strumenta_starlasu-ParsingResult-key", Name = "ParsingResult", Abstract = false, Partition = false, FeaturesLazy = new(() => [ParsingResult_code, ParsingResult_issues, ParsingResult_root, ParsingResult_tokens]) });
		_parsingResult_code = new(() => new PropertyBase<StarLasuLanguage>("com-strumenta-StarLasu-ParsingResult-code-id", ParsingResult, this) { Key = "com_strumenta_starlasu-ParsingResult-code-key", Name = "code", Optional = true, Type = _builtIns.String });
		_parsingResult_issues = new(() => new ContainmentBase<StarLasuLanguage>("com-strumenta-StarLasu-ParsingResult-issues-id", ParsingResult, this) { Key = "com_strumenta_starlasu-ParsingResult-issues-key", Name = "issues", Optional = true, Multiple = true, Type = Issue });
		_parsingResult_root = new(() => new ContainmentBase<StarLasuLanguage>("com-strumenta-StarLasu-ParsingResult-root-id", ParsingResult, this) { Key = "com_strumenta_starlasu-ParsingResult-root-key", Name = "root", Optional = true, Multiple = false, Type = ASTNode });
		_parsingResult_tokens = new(() => new PropertyBase<StarLasuLanguage>("com-strumenta-StarLasu-ParsingResult-tokens-id", ParsingResult, this) { Key = "com_strumenta_starlasu-ParsingResult-tokens-key", Name = "tokens", Optional = true, Type = TokensList });
		_placeholderElement = new(() => new InterfaceBase<StarLasuLanguage>("com-strumenta-StarLasu-PlaceholderElement-id", this) { Key = "com_strumenta_starlasu-PlaceholderElement-key", Name = "PlaceholderElement", ExtendsLazy = new(() => [CommonElement]) });
		_placeholderNode = new(() => new AnnotationBase<StarLasuLanguage>("com-strumenta-StarLasu-PlaceholderNode-id", this) { Key = "com_strumenta_starlasu-PlaceholderNode-key", Name = "PlaceholderNode", AnnotatesLazy = new(() => _m3.Concept), FeaturesLazy = new(() => [PlaceholderNode_message, PlaceholderNode_originalNode, PlaceholderNode_type]) });
		_placeholderNode_message = new(() => new PropertyBase<StarLasuLanguage>("com-strumenta-StarLasu-PlaceholderNode-message-id", PlaceholderNode, this) { Key = "com_strumenta_starlasu-PlaceholderNode-message-key", Name = "message", Optional = false, Type = _builtIns.String });
		_placeholderNode_originalNode = new(() => new ReferenceBase<StarLasuLanguage>("com-strumenta-StarLasu-PlaceholderNode-originalNode-id", PlaceholderNode, this) { Key = "com_strumenta_starlasu-PlaceholderNode-originalNode-key", Name = "originalNode", Optional = true, Multiple = false, Type = ASTNode });
		_placeholderNode_type = new(() => new PropertyBase<StarLasuLanguage>("com-strumenta-StarLasu-PlaceholderNode-type-id", PlaceholderNode, this) { Key = "com_strumenta_starlasu-PlaceholderNode-type-key", Name = "type", Optional = false, Type = PlaceholderNodeType });
		_placeholderNodeType = new(() => new EnumerationBase<StarLasuLanguage>("com-strumenta-StarLasu-PlaceholderNode-PlaceholderNodeType-id", this) { Key = "com_strumenta_starlasu-PlaceholderNode-PlaceholderNodeType-key", Name = "PlaceholderNodeType", LiteralsLazy = new(() => [PlaceholderNodeType_FailingASTTransformation, PlaceholderNodeType_MissingASTTransformation]) });
		_placeholderNodeType_FailingASTTransformation = new(() => new EnumerationLiteralBase<StarLasuLanguage>("com-strumenta-StarLasu-PlaceholderNode-PlaceholderNodeType-FailingASTTransformation-id", PlaceholderNodeType, this) { Key = "com-strumenta-StarLasu-PlaceholderNode-PlaceholderNodeType-id-FailingASTTransformation-key", Name = "FailingASTTransformation" });
		_placeholderNodeType_MissingASTTransformation = new(() => new EnumerationLiteralBase<StarLasuLanguage>("com-strumenta-StarLasu-PlaceholderNode-PlaceholderNodeType-MissingASTTransformation-id", PlaceholderNodeType, this) { Key = "com-strumenta-StarLasu-PlaceholderNode-PlaceholderNodeType-id-MissingASTTransformation-key", Name = "MissingASTTransformation" });
		_point = new(() => new PrimitiveTypeBase<StarLasuLanguage>("com-strumenta-StarLasu-Point-id", this) { Key = "com_strumenta_starlasu-Point-key", Name = "Point" });
		_position = new(() => new PrimitiveTypeBase<StarLasuLanguage>("com-strumenta-StarLasu-Position-id", this) { Key = "com_strumenta_starlasu-Position-key", Name = "Position" });
		_statement = new(() => new InterfaceBase<StarLasuLanguage>("com-strumenta-StarLasu-Statement-id", this) { Key = "com_strumenta_starlasu-Statement-key", Name = "Statement", ExtendsLazy = new(() => [CommonElement]) });
		_tokensList = new(() => new PrimitiveTypeBase<StarLasuLanguage>("com-strumenta-StarLasu-TokensList-id", this) { Key = "com_strumenta_starlasu-TokensList-key", Name = "TokensList" });
		_typeAnnotation = new(() => new InterfaceBase<StarLasuLanguage>("com-strumenta-StarLasu-TypeAnnotation-id", this) { Key = "com_strumenta_starlasu-TypeAnnotation-key", Name = "TypeAnnotation", ExtendsLazy = new(() => [CommonElement]) });
		_factory = new StarLasuFactory(this);
	}

	/// <inheritdoc/>
        public override IReadOnlyList<LanguageEntity> Entities => [ASTNode, BehaviorDeclaration, Char, CommonElement, Documentation, EntityDeclaration, EntityGroupDeclaration, Expression, Issue, IssueSeverity, IssueType, Parameter, ParsingResult, PlaceholderElement, PlaceholderNode, PlaceholderNodeType, Point, Position, Statement, TokensList, TypeAnnotation];
	/// <inheritdoc/>
        public override IReadOnlyList<Language> DependsOn => [];

	private const string _key = "com_strumenta_starlasu";
	/// <inheritdoc/>
        public override string Key => _key;

	private const string _name = "com.strumenta.StarLasu";
	/// <inheritdoc/>
        public override string Name => _name;

	private const string _version = "1";
	/// <inheritdoc/>
        public override string Version => _version;

	private readonly Lazy<Concept> _aSTNode;
	public Concept ASTNode => _aSTNode.Value;

	private readonly Lazy<Reference> _aSTNode_originalNode;
	public Reference ASTNode_originalNode => _aSTNode_originalNode.Value;

	private readonly Lazy<Property> _aSTNode_position;
	public Property ASTNode_position => _aSTNode_position.Value;

	private readonly Lazy<Reference> _aSTNode_transpiledNodes;
	public Reference ASTNode_transpiledNodes => _aSTNode_transpiledNodes.Value;

	private readonly Lazy<Interface> _behaviorDeclaration;
	public Interface BehaviorDeclaration => _behaviorDeclaration.Value;

	private readonly Lazy<PrimitiveType> _char;
	public PrimitiveType Char => _char.Value;

	private readonly Lazy<Interface> _commonElement;
	public Interface CommonElement => _commonElement.Value;

	private readonly Lazy<Interface> _documentation;
	public Interface Documentation => _documentation.Value;

	private readonly Lazy<Interface> _entityDeclaration;
	public Interface EntityDeclaration => _entityDeclaration.Value;

	private readonly Lazy<Interface> _entityGroupDeclaration;
	public Interface EntityGroupDeclaration => _entityGroupDeclaration.Value;

	private readonly Lazy<Interface> _expression;
	public Interface Expression => _expression.Value;

	private readonly Lazy<Concept> _issue;
	public Concept Issue => _issue.Value;

	private readonly Lazy<Property> _issue_message;
	public Property Issue_message => _issue_message.Value;

	private readonly Lazy<Property> _issue_position;
	public Property Issue_position => _issue_position.Value;

	private readonly Lazy<Property> _issue_severity;
	public Property Issue_severity => _issue_severity.Value;

	private readonly Lazy<Property> _issue_type;
	public Property Issue_type => _issue_type.Value;

	private readonly Lazy<Enumeration> _issueSeverity;
	public Enumeration IssueSeverity => _issueSeverity.Value;

	private readonly Lazy<EnumerationLiteral> _issueSeverity_ERROR;
	public EnumerationLiteral IssueSeverity_ERROR => _issueSeverity_ERROR.Value;

	private readonly Lazy<EnumerationLiteral> _issueSeverity_INFO;
	public EnumerationLiteral IssueSeverity_INFO => _issueSeverity_INFO.Value;

	private readonly Lazy<EnumerationLiteral> _issueSeverity_WARNING;
	public EnumerationLiteral IssueSeverity_WARNING => _issueSeverity_WARNING.Value;

	private readonly Lazy<Enumeration> _issueType;
	public Enumeration IssueType => _issueType.Value;

	private readonly Lazy<EnumerationLiteral> _issueType_LEXICAL;
	public EnumerationLiteral IssueType_LEXICAL => _issueType_LEXICAL.Value;

	private readonly Lazy<EnumerationLiteral> _issueType_SEMANTIC;
	public EnumerationLiteral IssueType_SEMANTIC => _issueType_SEMANTIC.Value;

	private readonly Lazy<EnumerationLiteral> _issueType_SYNTACTIC;
	public EnumerationLiteral IssueType_SYNTACTIC => _issueType_SYNTACTIC.Value;

	private readonly Lazy<EnumerationLiteral> _issueType_TRANSLATION;
	public EnumerationLiteral IssueType_TRANSLATION => _issueType_TRANSLATION.Value;

	private readonly Lazy<Interface> _parameter;
	public Interface Parameter => _parameter.Value;

	private readonly Lazy<Concept> _parsingResult;
	public Concept ParsingResult => _parsingResult.Value;

	private readonly Lazy<Property> _parsingResult_code;
	public Property ParsingResult_code => _parsingResult_code.Value;

	private readonly Lazy<Containment> _parsingResult_issues;
	public Containment ParsingResult_issues => _parsingResult_issues.Value;

	private readonly Lazy<Containment> _parsingResult_root;
	public Containment ParsingResult_root => _parsingResult_root.Value;

	private readonly Lazy<Property> _parsingResult_tokens;
	public Property ParsingResult_tokens => _parsingResult_tokens.Value;

	private readonly Lazy<Interface> _placeholderElement;
	public Interface PlaceholderElement => _placeholderElement.Value;

	private readonly Lazy<Annotation> _placeholderNode;
	public Annotation PlaceholderNode => _placeholderNode.Value;

	private readonly Lazy<Property> _placeholderNode_message;
	public Property PlaceholderNode_message => _placeholderNode_message.Value;

	private readonly Lazy<Reference> _placeholderNode_originalNode;
	public Reference PlaceholderNode_originalNode => _placeholderNode_originalNode.Value;

	private readonly Lazy<Property> _placeholderNode_type;
	public Property PlaceholderNode_type => _placeholderNode_type.Value;

	private readonly Lazy<Enumeration> _placeholderNodeType;
	public Enumeration PlaceholderNodeType => _placeholderNodeType.Value;

	private readonly Lazy<EnumerationLiteral> _placeholderNodeType_FailingASTTransformation;
	public EnumerationLiteral PlaceholderNodeType_FailingASTTransformation => _placeholderNodeType_FailingASTTransformation.Value;

	private readonly Lazy<EnumerationLiteral> _placeholderNodeType_MissingASTTransformation;
	public EnumerationLiteral PlaceholderNodeType_MissingASTTransformation => _placeholderNodeType_MissingASTTransformation.Value;

	private readonly Lazy<PrimitiveType> _point;
	public PrimitiveType Point => _point.Value;

	private readonly Lazy<PrimitiveType> _position;
	public PrimitiveType Position => _position.Value;

	private readonly Lazy<Interface> _statement;
	public Interface Statement => _statement.Value;

	private readonly Lazy<PrimitiveType> _tokensList;
	public PrimitiveType TokensList => _tokensList.Value;

	private readonly Lazy<Interface> _typeAnnotation;
	public Interface TypeAnnotation => _typeAnnotation.Value;
}

public partial interface IStarLasuFactory : INodeFactory
{
	public ASTNode NewASTNode(string id);
	public ASTNode CreateASTNode();
	public Issue NewIssue(string id);
	public Issue CreateIssue();
	public ParsingResult NewParsingResult(string id);
	public ParsingResult CreateParsingResult();
	public PlaceholderNode NewPlaceholderNode(string id);
	public PlaceholderNode CreatePlaceholderNode();
}

public class StarLasuFactory : AbstractBaseNodeFactory, IStarLasuFactory
{
	private readonly StarLasuLanguage _language;
	public StarLasuFactory(StarLasuLanguage language) : base(language)
	{
		_language = language;
	}

	/// <inheritdoc/>
        public override INode CreateNode(string id, Classifier classifier)
	{
		if (_language.ASTNode.EqualsIdentity(classifier))
			return NewASTNode(id);
		if (_language.Issue.EqualsIdentity(classifier))
			return NewIssue(id);
		if (_language.ParsingResult.EqualsIdentity(classifier))
			return NewParsingResult(id);
		if (_language.PlaceholderNode.EqualsIdentity(classifier))
			return NewPlaceholderNode(id);
		throw new UnsupportedClassifierException(classifier);
	}

	/// <inheritdoc/>
        public override Enum GetEnumerationLiteral(EnumerationLiteral literal)
	{
		if (_language.IssueSeverity.EqualsIdentity(literal.GetEnumeration()))
			return EnumValueFor<IssueSeverity>(literal);
		if (_language.IssueType.EqualsIdentity(literal.GetEnumeration()))
			return EnumValueFor<IssueType>(literal);
		if (_language.PlaceholderNodeType.EqualsIdentity(literal.GetEnumeration()))
			return EnumValueFor<PlaceholderNodeType>(literal);
		throw new UnsupportedEnumerationLiteralException(literal);
	}

	/// <inheritdoc/>
        public override IStructuredDataTypeInstance CreateStructuredDataTypeInstance(StructuredDataType structuredDataType, IFieldValues fieldValues)
	{
		throw new UnsupportedStructuredDataTypeException(structuredDataType);
	}

	public virtual ASTNode NewASTNode(string id) => new(id);
	public virtual ASTNode CreateASTNode() => NewASTNode(GetNewId());
	public virtual Issue NewIssue(string id) => new(id);
	public virtual Issue CreateIssue() => NewIssue(GetNewId());
	public virtual ParsingResult NewParsingResult(string id) => new(id);
	public virtual ParsingResult CreateParsingResult() => NewParsingResult(GetNewId());
	public virtual PlaceholderNode NewPlaceholderNode(string id) => new(id);
	public virtual PlaceholderNode CreatePlaceholderNode() => NewPlaceholderNode(GetNewId());
}

[LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "com_strumenta_starlasu-ASTNode-key")]
public partial class ASTNode : ConceptInstanceBase
{
	private ReferenceTarget? _originalNode = null;
	/// <remarks>Optional Single Reference</remarks>
        [LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "com_strumenta_starlasu-ASTNode-originalNode-key")]
	[LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = false)]
	public ASTNode? OriginalNode { get => ReferenceTargetNonNullTarget<ASTNode>(_originalNode, StarLasuLanguage.Instance.ASTNode_originalNode); set => SetOriginalNode(value); }

	/// <remarks>Optional Single Reference</remarks>
        public bool TryGetOriginalNode([NotNullWhenAttribute(true)] out ASTNode? originalNode)
	{
		originalNode = ReferenceTargetNullableTarget<ASTNode>(_originalNode, StarLasuLanguage.Instance.ASTNode_originalNode);
		return originalNode != null;
	}

	private ASTNode SetOriginalNode(ReferenceTarget? value)
	{
		SetOptionalSingleReference<ASTNode>(value, StarLasuLanguage.Instance.ASTNode_originalNode, _originalNode, SetOriginalNodeRaw);
		return this;
	}

	private bool SetOriginalNodeRaw(ReferenceTarget? value)
	{
		if (value == _originalNode)
			return false;
		_originalNode = value;
		return true;
	}

	/// <remarks>Optional Single Reference</remarks>
        public ASTNode SetOriginalNode(ASTNode? value)
	{
		return SetOriginalNode(ReferenceTarget.FromNodeOptional(value));
	}

	protected global::Strumenta.Sharplasu.Model.Position? _position = null;
	/// <remarks>Optional Property</remarks>
        [LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "com_strumenta_starlasu-ASTNode-position-key")]
	[LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = true, Multiple = false)]
	public virtual global::Strumenta.Sharplasu.Model.Position? Position { get => _position; set => SetPosition(value); }

	/// <remarks>Optional Property</remarks>
        public bool TryGetPosition([NotNullWhenAttribute(true)] out global::Strumenta.Sharplasu.Model.Position? position)
	{
		position = _position;
		return position != null;
	}

	private bool SetPositionRaw(global::Strumenta.Sharplasu.Model.Position? value)
	{
		if (value == _position)
			return false;
		_position = value;
		return true;
	}

	/// <remarks>Optional Property</remarks>
        public ASTNode SetPosition(global::Strumenta.Sharplasu.Model.Position? value)
	{
		SetOptionalReferenceTypeProperty<global::Strumenta.Sharplasu.Model.Position>(value, StarLasuLanguage.Instance.ASTNode_position, _position, SetPositionRaw);
		return this;
	}

	private readonly List<ReferenceTarget> _transpiledNodes = [];
	/// <remarks>Optional Multiple Reference</remarks>
        [LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "com_strumenta_starlasu-ASTNode-transpiledNodes-key")]
	[LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
    [JsonIgnore]
    [XmlIgnore]
    public IReadOnlyList<ASTNode> TranspiledNodes { get => ReferenceTargetNonNullTargets<ASTNode>(_transpiledNodes, StarLasuLanguage.Instance.ASTNode_transpiledNodes); init => AddTranspiledNodes(value); }

	/// <remarks>Optional Multiple Reference</remarks>
        public bool TryGetTranspiledNodes([NotNullWhenAttribute(true)] out IReadOnlyList<ASTNode> transpiledNodes) => TryGetReference<ASTNode>(_transpiledNodes, out transpiledNodes);
	private bool SetTranspiledNodesRaw(List<ReferenceTarget> targets) => SetReferencesRaw(targets, _transpiledNodes);
	private bool AddTranspiledNodesRaw(ReferenceTarget target) => AddReferencesRaw(target, _transpiledNodes);
	private bool InsertTranspiledNodesRaw(int index, ReferenceTarget target) => InsertReferencesRaw(index, target, _transpiledNodes);
	private bool RemoveTranspiledNodesRaw(ReferenceTarget target) => RemoveReferencesRaw(target, _transpiledNodes);
	/// <remarks>Optional Multiple Reference</remarks>
        public ASTNode AddTranspiledNodes(IEnumerable<ASTNode> nodes)
	{
		AddOptionalMultipleReference<ASTNode>(nodes, StarLasuLanguage.Instance.ASTNode_transpiledNodes, _transpiledNodes, AddTranspiledNodesRaw);
		return this;
	}

	/// <remarks>Optional Multiple Reference</remarks>
        public ASTNode InsertTranspiledNodes(int index, IEnumerable<ASTNode> nodes)
	{
		InsertOptionalMultipleReference<ASTNode>(index, nodes, StarLasuLanguage.Instance.ASTNode_transpiledNodes, _transpiledNodes, InsertTranspiledNodesRaw);
		return this;
	}

	/// <remarks>Optional Multiple Reference</remarks>
        public ASTNode RemoveTranspiledNodes(IEnumerable<ASTNode> nodes)
	{
		RemoveOptionalMultipleReference<ASTNode>(nodes, StarLasuLanguage.Instance.ASTNode_transpiledNodes, _transpiledNodes, RemoveTranspiledNodesRaw);
		return this;
	}

	public ASTNode(string id) : base(id)
	{
	}

	/// <inheritdoc/>
        public override Concept GetConcept() => StarLasuLanguage.Instance.ASTNode;
	/// <inheritdoc/>
        protected override bool GetInternal(Feature? feature, out object? result)
	{
		if (base.GetInternal(feature, out result))
			return true;
		if (StarLasuLanguage.Instance.ASTNode_originalNode.EqualsIdentity(feature))
		{
			result = OriginalNode;
			return true;
		}

		if (StarLasuLanguage.Instance.ASTNode_position.EqualsIdentity(feature))
		{
			result = Position;
			return true;
		}

		if (StarLasuLanguage.Instance.ASTNode_transpiledNodes.EqualsIdentity(feature))
		{
			result = TranspiledNodes;
			return true;
		}

		return false;
	}

	protected override bool TryGetPropertyRaw(Property feature, out object? result)
	{
		if (base.TryGetPropertyRaw(feature, out result))
			return true;
		if (StarLasuLanguage.Instance.ASTNode_position.EqualsIdentity(feature))
		{
			result = _position;
			return true;
		}

		return false;
	}

	protected override bool TryGetReferenceRaw(Reference feature, out IReferenceTarget? result)
	{
		if (base.TryGetReferenceRaw(feature, out result))
			return true;
		if (StarLasuLanguage.Instance.ASTNode_originalNode.EqualsIdentity(feature))
		{
			result = _originalNode;
			return true;
		}

		return false;
	}

	protected override bool TryGetReferencesRaw(Reference feature, out IReadOnlyList<IReferenceTarget> result)
	{
		if (base.TryGetReferencesRaw(feature, out result))
			return true;
		if (StarLasuLanguage.Instance.ASTNode_transpiledNodes.EqualsIdentity(feature))
		{
			result = _transpiledNodes;
			return true;
		}

		return false;
	}

	/// <inheritdoc/>
        protected override bool SetInternal(Feature? feature, object? value)
	{
		if (base.SetInternal(feature, value))
			return true;
		if (StarLasuLanguage.Instance.ASTNode_originalNode.EqualsIdentity(feature))
		{
			if (value is null or com.strumenta.starlasu.ASTNode)
			{
				SetOriginalNode((com.strumenta.starlasu.ASTNode?)value);
				return true;
			}

			if (value is ReferenceTarget target)
			{
				SetOriginalNode(target);
				return true;
			}

			throw new InvalidValueException(feature, value);
		}

		if (StarLasuLanguage.Instance.ASTNode_position.EqualsIdentity(feature))
		{
			if (value is null or global::Strumenta.Sharplasu.Model.Position)
			{
				SetPosition((global::Strumenta.Sharplasu.Model.Position?)value);
				return true;
			}

			throw new InvalidValueException(feature, value);
		}

		if (StarLasuLanguage.Instance.ASTNode_transpiledNodes.EqualsIdentity(feature))
		{
			SetOptionalMultipleReference<ASTNode>(value, StarLasuLanguage.Instance.ASTNode_transpiledNodes, _transpiledNodes, SetTranspiledNodesRaw);
			return true;
		}

		return false;
	}

	protected override bool SetPropertyRaw(Property feature, object? value)
	{
		if (base.SetPropertyRaw(feature, value))
			return true;
		if (StarLasuLanguage.Instance.ASTNode_position.EqualsIdentity(feature) && value is null or global::Strumenta.Sharplasu.Model.Position)
			return SetPositionRaw((global::Strumenta.Sharplasu.Model.Position?)value);
		return false;
	}

	protected override bool SetReferenceRaw(Reference feature, ReferenceTarget? value)
	{
		if (base.SetReferenceRaw(feature, value))
			return true;
		if (StarLasuLanguage.Instance.ASTNode_originalNode.EqualsIdentity(feature))
			return SetOriginalNodeRaw(value);
		return false;
	}

	/// <inheritdoc/>
        public override IEnumerable<Feature> CollectAllSetFeatures()
	{
		List<Feature> result = base.CollectAllSetFeatures().ToList();
		if (TryGetOriginalNode(out _))
			result.Add(StarLasuLanguage.Instance.ASTNode_originalNode);
		if (TryGetPosition(out _))
			result.Add(StarLasuLanguage.Instance.ASTNode_position);
		if (TryGetTranspiledNodes(out _))
			result.Add(StarLasuLanguage.Instance.ASTNode_transpiledNodes);
		return result;
	}

	protected override bool AddReferencesRaw(Reference feature, ReferenceTarget value)
	{
		if (base.AddReferencesRaw(feature, value))
			return true;
		if (StarLasuLanguage.Instance.ASTNode_transpiledNodes.EqualsIdentity(feature))
			return AddTranspiledNodesRaw(value);
		return false;
	}

	protected override bool InsertReferencesRaw(Reference feature, int index, ReferenceTarget value)
	{
		if (base.InsertReferencesRaw(feature, index, value))
			return true;
		if (StarLasuLanguage.Instance.ASTNode_transpiledNodes.EqualsIdentity(feature))
			return InsertTranspiledNodesRaw(index, value);
		return false;
	}

	protected override bool RemoveReferencesRaw(Reference feature, ReferenceTarget value)
	{
		if (base.RemoveReferencesRaw(feature, value))
			return true;
		if (StarLasuLanguage.Instance.ASTNode_transpiledNodes.EqualsIdentity(feature))
			return RemoveTranspiledNodesRaw(value);
		return false;
	}

	/// <inheritdoc/>
        protected override bool AddInternal(Link? link, IEnumerable<IReadableNode> value)
	{
		if (base.AddInternal(link, value))
			return true;
		if (StarLasuLanguage.Instance.ASTNode_transpiledNodes.EqualsIdentity(link))
		{
			AddTranspiledNodes(StarLasuLanguage.Instance.ASTNode_transpiledNodes.AsNodes<com.strumenta.starlasu.ASTNode>(value));
			return true;
		}

		return false;
	}

	/// <inheritdoc/>
        protected override bool InsertInternal(Link? link, int index, IEnumerable<IReadableNode> value)
	{
		if (base.InsertInternal(link, index, value))
			return true;
		if (StarLasuLanguage.Instance.ASTNode_transpiledNodes.EqualsIdentity(link))
		{
			InsertTranspiledNodes(index, StarLasuLanguage.Instance.ASTNode_transpiledNodes.AsNodes<com.strumenta.starlasu.ASTNode>(value));
			return true;
		}

		return false;
	}

	/// <inheritdoc/>
        protected override bool RemoveInternal(Link? link, IEnumerable<IReadableNode> value)
	{
		if (base.RemoveInternal(link, value))
			return true;
		if (StarLasuLanguage.Instance.ASTNode_transpiledNodes.EqualsIdentity(link))
		{
			RemoveTranspiledNodes(StarLasuLanguage.Instance.ASTNode_transpiledNodes.AsNodes<com.strumenta.starlasu.ASTNode>(value));
			return true;
		}

		return false;
	}
}

[LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "com_strumenta_starlasu-BehaviorDeclaration-key")]
public partial interface BehaviorDeclaration : CommonElement
{
}

[LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "com_strumenta_starlasu-CommonElement-key")]
public partial interface CommonElement : INode
{
}

[LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "com_strumenta_starlasu-Documentation-key")]
public partial interface Documentation : CommonElement
{
}

[LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "com_strumenta_starlasu-EntityDeclaration-key")]
public partial interface EntityDeclaration : CommonElement
{
}

[LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "com_strumenta_starlasu-EntityGroupDeclaration-key")]
public partial interface EntityGroupDeclaration : CommonElement
{
}

[LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "com_strumenta_starlasu-Expression-key")]
public partial interface Expression : CommonElement
{
}

[LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "com_strumenta_starlasu-Issue-key")]
public partial class Issue : ConceptInstanceBase
{
	private string? _message = null;
	private bool SetMessageRaw(string? value)
	{
		if (value == _message)
			return false;
		_message = value;
		return true;
	}

	/// <remarks>Required Property</remarks>
    	/// <exception cref = "UnsetFeatureException">If Message has not been set</exception>
    	/// <exception cref = "InvalidValueException">If set to null</exception>
        [LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "com_strumenta_starlasu-Issue-message-key")]
	[LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = false, Multiple = false)]
	public string Message { get => _message ?? throw new UnsetFeatureException(StarLasuLanguage.Instance.Issue_message); set => SetMessage(value); }

	/// <remarks>Required Property</remarks>
    	/// <exception cref = "InvalidValueException">If set to null</exception>
        public bool TryGetMessage([NotNullWhenAttribute(true)] out string? message)
	{
		message = _message;
		return message != null;
	}

	/// <remarks>Required Property</remarks>
    	/// <exception cref = "InvalidValueException">If set to null</exception>
        public Issue SetMessage(string value)
	{
		SetRequiredReferenceTypeProperty<string>(value, StarLasuLanguage.Instance.Issue_message, _message, SetMessageRaw);
		return this;
	}

	private global::Strumenta.Sharplasu.Model.Position? _position = null;
	/// <remarks>Optional Property</remarks>
        [LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "com_strumenta_starlasu-Issue-position-key")]
	[LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = true, Multiple = false)]
	public global::Strumenta.Sharplasu.Model.Position? Position { get => _position; set => SetPosition(value); }

	/// <remarks>Optional Property</remarks>
        public bool TryGetPosition([NotNullWhenAttribute(true)] out global::Strumenta.Sharplasu.Model.Position? position)
	{
		position = _position;
		return position != null;
	}

	private bool SetPositionRaw(global::Strumenta.Sharplasu.Model.Position? value)
	{
		if (value == _position)
			return false;
		_position = value;
		return true;
	}

	/// <remarks>Optional Property</remarks>
        public Issue SetPosition(global::Strumenta.Sharplasu.Model.Position? value)
	{
		SetOptionalReferenceTypeProperty<global::Strumenta.Sharplasu.Model.Position>(value, StarLasuLanguage.Instance.Issue_position, _position, SetPositionRaw);
		return this;
	}

	private IssueSeverity? _severity = null;
	private bool SetSeverityRaw(IssueSeverity? value)
	{
		if (value == _severity)
			return false;
		_severity = value;
		return true;
	}

	/// <remarks>Required Property</remarks>
    	/// <exception cref = "UnsetFeatureException">If Severity has not been set</exception>
        [LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "com_strumenta_starlasu-Issue-severity-key")]
	[LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = false, Multiple = false)]
	public IssueSeverity Severity { get => _severity ?? throw new UnsetFeatureException(StarLasuLanguage.Instance.Issue_severity); set => SetSeverity(value); }

	/// <remarks>Required Property</remarks>
        public bool TryGetSeverity([NotNullWhenAttribute(true)] out IssueSeverity? severity)
	{
		severity = _severity;
		return severity != null;
	}

	/// <remarks>Required Property</remarks>
        public Issue SetSeverity(IssueSeverity value)
	{
		SetRequiredValueTypeProperty<IssueSeverity>(value, StarLasuLanguage.Instance.Issue_severity, _severity, SetSeverityRaw);
		return this;
	}

	private IssueType? _type = null;
	private bool SetTypeRaw(IssueType? value)
	{
		if (value == _type)
			return false;
		_type = value;
		return true;
	}

	/// <remarks>Required Property</remarks>
    	/// <exception cref = "UnsetFeatureException">If Type has not been set</exception>
        [LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "com_strumenta_starlasu-Issue-type-key")]
	[LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = false, Multiple = false)]
	public IssueType Type { get => _type ?? throw new UnsetFeatureException(StarLasuLanguage.Instance.Issue_type); set => SetType(value); }

	/// <remarks>Required Property</remarks>
        public bool TryGetType([NotNullWhenAttribute(true)] out IssueType? @type)
	{
		@type = _type;
		return @type != null;
	}

	/// <remarks>Required Property</remarks>
        public Issue SetType(IssueType value)
	{
		SetRequiredValueTypeProperty<IssueType>(value, StarLasuLanguage.Instance.Issue_type, _type, SetTypeRaw);
		return this;
	}

	public Issue(string id) : base(id)
	{
	}

	/// <inheritdoc/>
        public override Concept GetConcept() => StarLasuLanguage.Instance.Issue;
	/// <inheritdoc/>
        protected override bool GetInternal(Feature? feature, out object? result)
	{
		if (base.GetInternal(feature, out result))
			return true;
		if (StarLasuLanguage.Instance.Issue_message.EqualsIdentity(feature))
		{
			result = Message;
			return true;
		}

		if (StarLasuLanguage.Instance.Issue_position.EqualsIdentity(feature))
		{
			result = Position;
			return true;
		}

		if (StarLasuLanguage.Instance.Issue_severity.EqualsIdentity(feature))
		{
			result = Severity;
			return true;
		}

		if (StarLasuLanguage.Instance.Issue_type.EqualsIdentity(feature))
		{
			result = Type;
			return true;
		}

		return false;
	}

	protected override bool TryGetPropertyRaw(Property feature, out object? result)
	{
		if (base.TryGetPropertyRaw(feature, out result))
			return true;
		if (StarLasuLanguage.Instance.Issue_message.EqualsIdentity(feature))
		{
			result = _message;
			return true;
		}

		if (StarLasuLanguage.Instance.Issue_position.EqualsIdentity(feature))
		{
			result = _position;
			return true;
		}

		if (StarLasuLanguage.Instance.Issue_severity.EqualsIdentity(feature))
		{
			result = _severity;
			return true;
		}

		if (StarLasuLanguage.Instance.Issue_type.EqualsIdentity(feature))
		{
			result = _type;
			return true;
		}

		return false;
	}

	/// <inheritdoc/>
        protected override bool SetInternal(Feature? feature, object? value)
	{
		if (base.SetInternal(feature, value))
			return true;
		if (StarLasuLanguage.Instance.Issue_message.EqualsIdentity(feature))
		{
			if (value is string v)
			{
				SetMessage(v);
				return true;
			}

			throw new InvalidValueException(feature, value);
		}

		if (StarLasuLanguage.Instance.Issue_position.EqualsIdentity(feature))
		{
			if (value is null or global::Strumenta.Sharplasu.Model.Position)
			{
				SetPosition((global::Strumenta.Sharplasu.Model.Position?)value);
				return true;
			}

			throw new InvalidValueException(feature, value);
		}

		if (StarLasuLanguage.Instance.Issue_severity.EqualsIdentity(feature))
		{
			if (value is com.strumenta.starlasu.IssueSeverity v)
			{
				SetSeverity(v);
				return true;
			}

			throw new InvalidValueException(feature, value);
		}

		if (StarLasuLanguage.Instance.Issue_type.EqualsIdentity(feature))
		{
			if (value is com.strumenta.starlasu.IssueType v)
			{
				SetType(v);
				return true;
			}

			throw new InvalidValueException(feature, value);
		}

		return false;
	}

	protected override bool SetPropertyRaw(Property feature, object? value)
	{
		if (base.SetPropertyRaw(feature, value))
			return true;
		if (StarLasuLanguage.Instance.Issue_message.EqualsIdentity(feature) && value is null or string)
			return SetMessageRaw((string?)value);
		if (StarLasuLanguage.Instance.Issue_position.EqualsIdentity(feature) && value is null or global::Strumenta.Sharplasu.Model.Position)
			return SetPositionRaw((global::Strumenta.Sharplasu.Model.Position?)value);
		if (StarLasuLanguage.Instance.Issue_severity.EqualsIdentity(feature) && value is null or com.strumenta.starlasu.IssueSeverity)
			return SetSeverityRaw((com.strumenta.starlasu.IssueSeverity?)value);
		if (StarLasuLanguage.Instance.Issue_type.EqualsIdentity(feature) && value is null or com.strumenta.starlasu.IssueType)
			return SetTypeRaw((com.strumenta.starlasu.IssueType?)value);
		return false;
	}

	/// <inheritdoc/>
        public override IEnumerable<Feature> CollectAllSetFeatures()
	{
		List<Feature> result = base.CollectAllSetFeatures().ToList();
		if (TryGetMessage(out _))
			result.Add(StarLasuLanguage.Instance.Issue_message);
		if (TryGetPosition(out _))
			result.Add(StarLasuLanguage.Instance.Issue_position);
		if (TryGetSeverity(out _))
			result.Add(StarLasuLanguage.Instance.Issue_severity);
		if (TryGetType(out _))
			result.Add(StarLasuLanguage.Instance.Issue_type);
		return result;
	}
}

[LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "com_strumenta_starlasu-Parameter-key")]
public partial interface Parameter : CommonElement
{
}

[LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "com_strumenta_starlasu-ParsingResult-key")]
public partial class ParsingResult : ConceptInstanceBase
{
	private string? _code = null;
	/// <remarks>Optional Property</remarks>
        [LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "com_strumenta_starlasu-ParsingResult-code-key")]
	[LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = true, Multiple = false)]
	public string? Code { get => _code; set => SetCode(value); }

	/// <remarks>Optional Property</remarks>
        public bool TryGetCode([NotNullWhenAttribute(true)] out string? code)
	{
		code = _code;
		return code != null;
	}

	private bool SetCodeRaw(string? value)
	{
		if (value == _code)
			return false;
		_code = value;
		return true;
	}

	/// <remarks>Optional Property</remarks>
        public ParsingResult SetCode(string? value)
	{
		SetOptionalReferenceTypeProperty<string>(value, StarLasuLanguage.Instance.ParsingResult_code, _code, SetCodeRaw);
		return this;
	}

	private bool SetIssuesRaw(List<Issue> nodes) => ExchangeChildrenRaw(nodes, _issues);
	private bool AddIssuesRaw(Issue? value) => AddChildRaw(value, _issues);
	private bool InsertIssuesRaw(int index, Issue? value) => InsertChildRaw(index, value, _issues);
	private bool RemoveIssuesRaw(Issue? value) => RemoveChildRaw(value, _issues);
	private readonly List<Issue> _issues = [];
	/// <remarks>Optional Multiple Containment</remarks>
        [LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "com_strumenta_starlasu-ParsingResult-issues-key")]
	[LionCoreFeature(Kind = LionCoreFeatureKind.Containment, Optional = true, Multiple = true)]
	public IReadOnlyList<Issue> Issues { get => _issues.AsReadOnly(); init => AddIssues(value); }

	/// <remarks>Optional Multiple Containment</remarks>
        public bool TryGetIssues([NotNullWhenAttribute(true)] out IReadOnlyList<Issue> issues)
	{
		issues = _issues.AsReadOnly();
		return issues.Count != 0;
	}

	/// <remarks>Optional Multiple Containment</remarks>
        public ParsingResult AddIssues(IEnumerable<Issue> nodes)
	{
		AddOptionalMultipleContainment<Issue>(nodes, StarLasuLanguage.Instance.ParsingResult_issues, _issues, AddIssuesRaw);
		return this;
	}

	/// <remarks>Optional Multiple Containment</remarks>
        public ParsingResult InsertIssues(int index, IEnumerable<Issue> nodes)
	{
		InsertOptionalMultipleContainment<Issue>(index, nodes, StarLasuLanguage.Instance.ParsingResult_issues, _issues, InsertIssuesRaw);
		return this;
	}

	/// <remarks>Optional Multiple Containment</remarks>
        public ParsingResult RemoveIssues(IEnumerable<Issue> nodes)
	{
		RemoveOptionalMultipleContainment<Issue>(nodes, StarLasuLanguage.Instance.ParsingResult_issues, _issues, RemoveIssuesRaw);
		return this;
	}

	private ASTNode? _root = null;
	/// <remarks>Optional Single Containment</remarks>
        [LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "com_strumenta_starlasu-ParsingResult-root-key")]
	[LionCoreFeature(Kind = LionCoreFeatureKind.Containment, Optional = true, Multiple = false)]
	public ASTNode? Root { get => _root; set => SetRoot(value); }

	/// <remarks>Optional Single Containment</remarks>
        public bool TryGetRoot([NotNullWhenAttribute(true)] out ASTNode? root)
	{
		root = _root;
		return root != null;
	}

	private bool SetRootRaw(ASTNode? value)
	{
		if (!ExchangeChildRaw(value, _root))
			return false;
		_root = value;
		return true;
	}

	/// <remarks>Optional Single Containment</remarks>
        public ParsingResult SetRoot(ASTNode? value)
	{
		SetOptionalSingleContainment<ASTNode>(value, StarLasuLanguage.Instance.ParsingResult_root, _root, SetRootRaw);
		return this;
	}

	private TokensList? _tokens = null;
	/// <remarks>Optional Property</remarks>
        [LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "com_strumenta_starlasu-ParsingResult-tokens-key")]
	[LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = true, Multiple = false)]
	public TokensList? Tokens { get => _tokens; set => SetTokens(value); }

	/// <remarks>Optional Property</remarks>
        public bool TryGetTokens([NotNullWhenAttribute(true)] out TokensList? tokens)
	{
		tokens = _tokens;
		return tokens != null;
	}

	private bool SetTokensRaw(TokensList? value)
	{
		if (value == _tokens)
			return false;
		_tokens = value;
		return true;
	}

	/// <remarks>Optional Property</remarks>
        public ParsingResult SetTokens(TokensList? value)
	{
		SetOptionalReferenceTypeProperty<TokensList>(value, StarLasuLanguage.Instance.ParsingResult_tokens, _tokens, SetTokensRaw);
		return this;
	}

	public ParsingResult(string id) : base(id)
	{
	}

	/// <inheritdoc/>
        public override Concept GetConcept() => StarLasuLanguage.Instance.ParsingResult;
	/// <inheritdoc/>
        protected override bool GetInternal(Feature? feature, out object? result)
	{
		if (base.GetInternal(feature, out result))
			return true;
		if (StarLasuLanguage.Instance.ParsingResult_code.EqualsIdentity(feature))
		{
			result = Code;
			return true;
		}

		if (StarLasuLanguage.Instance.ParsingResult_issues.EqualsIdentity(feature))
		{
			result = Issues;
			return true;
		}

		if (StarLasuLanguage.Instance.ParsingResult_root.EqualsIdentity(feature))
		{
			result = Root;
			return true;
		}

		if (StarLasuLanguage.Instance.ParsingResult_tokens.EqualsIdentity(feature))
		{
			result = Tokens;
			return true;
		}

		return false;
	}

	protected override bool TryGetPropertyRaw(Property feature, out object? result)
	{
		if (base.TryGetPropertyRaw(feature, out result))
			return true;
		if (StarLasuLanguage.Instance.ParsingResult_code.EqualsIdentity(feature))
		{
			result = _code;
			return true;
		}

		if (StarLasuLanguage.Instance.ParsingResult_tokens.EqualsIdentity(feature))
		{
			result = _tokens;
			return true;
		}

		return false;
	}

	protected override bool TryGetContainmentRaw(Containment feature, out IReadableNode? result)
	{
		if (base.TryGetContainmentRaw(feature, out result))
			return true;
		if (StarLasuLanguage.Instance.ParsingResult_root.EqualsIdentity(feature))
		{
			result = _root;
			return true;
		}

		return false;
	}

	protected override bool TryGetContainmentsRaw(Containment feature, out IReadOnlyList<IReadableNode> result)
	{
		if (base.TryGetContainmentsRaw(feature, out result))
			return true;
		if (StarLasuLanguage.Instance.ParsingResult_issues.EqualsIdentity(feature))
		{
			result = _issues;
			return true;
		}

		return false;
	}

	/// <inheritdoc/>
        protected override bool SetInternal(Feature? feature, object? value)
	{
		if (base.SetInternal(feature, value))
			return true;
		if (StarLasuLanguage.Instance.ParsingResult_code.EqualsIdentity(feature))
		{
			if (value is null or string)
			{
				SetCode((string?)value);
				return true;
			}

			throw new InvalidValueException(feature, value);
		}

		if (StarLasuLanguage.Instance.ParsingResult_issues.EqualsIdentity(feature))
		{
			SetOptionalMultipleContainment<Issue>(value, StarLasuLanguage.Instance.ParsingResult_issues, _issues, SetIssuesRaw);
			return true;
		}

		if (StarLasuLanguage.Instance.ParsingResult_root.EqualsIdentity(feature))
		{
			if (value is null or com.strumenta.starlasu.ASTNode)
			{
				SetRoot((com.strumenta.starlasu.ASTNode?)value);
				return true;
			}

			throw new InvalidValueException(feature, value);
		}

		if (StarLasuLanguage.Instance.ParsingResult_tokens.EqualsIdentity(feature))
		{
			if (value is null or TokensList)
			{
				SetTokens((TokensList?)value);
				return true;
			}

			throw new InvalidValueException(feature, value);
		}

		return false;
	}

	protected override bool SetPropertyRaw(Property feature, object? value)
	{
		if (base.SetPropertyRaw(feature, value))
			return true;
		if (StarLasuLanguage.Instance.ParsingResult_code.EqualsIdentity(feature) && value is null or string)
			return SetCodeRaw((string?)value);
		if (StarLasuLanguage.Instance.ParsingResult_tokens.EqualsIdentity(feature) && value is null or TokensList)
			return SetTokensRaw((TokensList?)value);
		return false;
	}

	protected override bool SetContainmentRaw(Containment feature, IWritableNode? value)
	{
		if (base.SetContainmentRaw(feature, value))
			return true;
		if (StarLasuLanguage.Instance.ParsingResult_root.EqualsIdentity(feature) && value is null or com.strumenta.starlasu.ASTNode)
			return SetRootRaw((com.strumenta.starlasu.ASTNode?)value);
		return false;
	}

	/// <inheritdoc/>
        public override IEnumerable<Feature> CollectAllSetFeatures()
	{
		List<Feature> result = base.CollectAllSetFeatures().ToList();
		if (TryGetCode(out _))
			result.Add(StarLasuLanguage.Instance.ParsingResult_code);
		if (TryGetIssues(out _))
			result.Add(StarLasuLanguage.Instance.ParsingResult_issues);
		if (TryGetRoot(out _))
			result.Add(StarLasuLanguage.Instance.ParsingResult_root);
		if (TryGetTokens(out _))
			result.Add(StarLasuLanguage.Instance.ParsingResult_tokens);
		return result;
	}

	protected override bool AddContainmentsRaw(Containment feature, IWritableNode value)
	{
		if (base.AddContainmentsRaw(feature, value))
			return true;
		if (StarLasuLanguage.Instance.ParsingResult_issues.EqualsIdentity(feature) && value is com.strumenta.starlasu.Issue v0)
			return AddIssuesRaw(v0);
		return false;
	}

	protected override bool InsertContainmentsRaw(Containment feature, int index, IWritableNode value)
	{
		if (base.InsertContainmentsRaw(feature, index, value))
			return true;
		if (StarLasuLanguage.Instance.ParsingResult_issues.EqualsIdentity(feature) && value is com.strumenta.starlasu.Issue v0)
			return InsertIssuesRaw(index, v0);
		return false;
	}

	protected override bool RemoveContainmentsRaw(Containment feature, IWritableNode value)
	{
		if (base.RemoveContainmentsRaw(feature, value))
			return true;
		if (StarLasuLanguage.Instance.ParsingResult_issues.EqualsIdentity(feature) && value is com.strumenta.starlasu.Issue v0)
			return RemoveIssuesRaw(v0);
		return false;
	}

	/// <inheritdoc/>
        protected override bool AddInternal(Link? link, IEnumerable<IReadableNode> value)
	{
		if (base.AddInternal(link, value))
			return true;
		if (StarLasuLanguage.Instance.ParsingResult_issues.EqualsIdentity(link))
		{
			AddIssues(StarLasuLanguage.Instance.ParsingResult_issues.AsNodes<com.strumenta.starlasu.Issue>(value));
			return true;
		}

		return false;
	}

	/// <inheritdoc/>
        protected override bool InsertInternal(Link? link, int index, IEnumerable<IReadableNode> value)
	{
		if (base.InsertInternal(link, index, value))
			return true;
		if (StarLasuLanguage.Instance.ParsingResult_issues.EqualsIdentity(link))
		{
			InsertIssues(index, StarLasuLanguage.Instance.ParsingResult_issues.AsNodes<com.strumenta.starlasu.Issue>(value));
			return true;
		}

		return false;
	}

	/// <inheritdoc/>
        protected override bool RemoveInternal(Link? link, IEnumerable<IReadableNode> value)
	{
		if (base.RemoveInternal(link, value))
			return true;
		if (StarLasuLanguage.Instance.ParsingResult_issues.EqualsIdentity(link))
		{
			RemoveIssues(StarLasuLanguage.Instance.ParsingResult_issues.AsNodes<com.strumenta.starlasu.Issue>(value));
			return true;
		}

		return false;
	}

	/// <inheritdoc/>
        protected override bool DetachChild(INode child)
	{
		if (base.DetachChild(child))
			return true;
		Containment? c = GetContainmentOf(child);
		if (StarLasuLanguage.Instance.ParsingResult_issues.EqualsIdentity(c))
		{
			RemoveSelfParent(child, _issues, StarLasuLanguage.Instance.ParsingResult_issues);
			return true;
		}

		if (StarLasuLanguage.Instance.ParsingResult_root.EqualsIdentity(c))
		{
			_root = null;
			return true;
		}

		return false;
	}

	/// <inheritdoc/>
        public override Containment? GetContainmentOf(INode child)
	{
		Containment? result = base.GetContainmentOf(child);
		if (result != null)
			return result;
		if (child is Issue child0 && _issues.Contains(child0))
			return StarLasuLanguage.Instance.ParsingResult_issues;
		if (ReferenceEquals(_root, child))
			return StarLasuLanguage.Instance.ParsingResult_root;
		return null;
	}
}

[LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "com_strumenta_starlasu-PlaceholderElement-key")]
public partial interface PlaceholderElement : CommonElement
{
}

[LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "com_strumenta_starlasu-PlaceholderNode-key")]
public partial class PlaceholderNode : AnnotationInstanceBase
{
	private string? _message = null;
	private bool SetMessageRaw(string? value)
	{
		if (value == _message)
			return false;
		_message = value;
		return true;
	}

	/// <remarks>Required Property</remarks>
    	/// <exception cref = "UnsetFeatureException">If Message has not been set</exception>
    	/// <exception cref = "InvalidValueException">If set to null</exception>
        [LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "com_strumenta_starlasu-PlaceholderNode-message-key")]
	[LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = false, Multiple = false)]
	public string Message { get => _message ?? throw new UnsetFeatureException(StarLasuLanguage.Instance.PlaceholderNode_message); set => SetMessage(value); }

	/// <remarks>Required Property</remarks>
    	/// <exception cref = "InvalidValueException">If set to null</exception>
        public bool TryGetMessage([NotNullWhenAttribute(true)] out string? message)
	{
		message = _message;
		return message != null;
	}

	/// <remarks>Required Property</remarks>
    	/// <exception cref = "InvalidValueException">If set to null</exception>
        public PlaceholderNode SetMessage(string value)
	{
		SetRequiredReferenceTypeProperty<string>(value, StarLasuLanguage.Instance.PlaceholderNode_message, _message, SetMessageRaw);
		return this;
	}

	private ReferenceTarget? _originalNode = null;
	/// <remarks>Optional Single Reference</remarks>
        [LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "com_strumenta_starlasu-PlaceholderNode-originalNode-key")]
	[LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = false)]
	public ASTNode? OriginalNode { get => ReferenceTargetNonNullTarget<ASTNode>(_originalNode, StarLasuLanguage.Instance.PlaceholderNode_originalNode); set => SetOriginalNode(value); }

	/// <remarks>Optional Single Reference</remarks>
        public bool TryGetOriginalNode([NotNullWhenAttribute(true)] out ASTNode? originalNode)
	{
		originalNode = ReferenceTargetNullableTarget<ASTNode>(_originalNode, StarLasuLanguage.Instance.PlaceholderNode_originalNode);
		return originalNode != null;
	}

	private PlaceholderNode SetOriginalNode(ReferenceTarget? value)
	{
		SetOptionalSingleReference<ASTNode>(value, StarLasuLanguage.Instance.PlaceholderNode_originalNode, _originalNode, SetOriginalNodeRaw);
		return this;
	}

	private bool SetOriginalNodeRaw(ReferenceTarget? value)
	{
		if (value == _originalNode)
			return false;
		_originalNode = value;
		return true;
	}

	/// <remarks>Optional Single Reference</remarks>
        public PlaceholderNode SetOriginalNode(ASTNode? value)
	{
		return SetOriginalNode(ReferenceTarget.FromNodeOptional(value));
	}

	private PlaceholderNodeType? _type = null;
	private bool SetTypeRaw(PlaceholderNodeType? value)
	{
		if (value == _type)
			return false;
		_type = value;
		return true;
	}

	/// <remarks>Required Property</remarks>
    	/// <exception cref = "UnsetFeatureException">If Type has not been set</exception>
        [LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "com_strumenta_starlasu-PlaceholderNode-type-key")]
	[LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = false, Multiple = false)]
	public PlaceholderNodeType Type { get => _type ?? throw new UnsetFeatureException(StarLasuLanguage.Instance.PlaceholderNode_type); set => SetType(value); }

	/// <remarks>Required Property</remarks>
        public bool TryGetType([NotNullWhenAttribute(true)] out PlaceholderNodeType? @type)
	{
		@type = _type;
		return @type != null;
	}

	/// <remarks>Required Property</remarks>
        public PlaceholderNode SetType(PlaceholderNodeType value)
	{
		SetRequiredValueTypeProperty<PlaceholderNodeType>(value, StarLasuLanguage.Instance.PlaceholderNode_type, _type, SetTypeRaw);
		return this;
	}

	public PlaceholderNode(string id) : base(id)
	{
	}

	/// <inheritdoc/>
        public override Annotation GetAnnotation() => StarLasuLanguage.Instance.PlaceholderNode;
	/// <inheritdoc/>
        protected override bool GetInternal(Feature? feature, out object? result)
	{
		if (base.GetInternal(feature, out result))
			return true;
		if (StarLasuLanguage.Instance.PlaceholderNode_message.EqualsIdentity(feature))
		{
			result = Message;
			return true;
		}

		if (StarLasuLanguage.Instance.PlaceholderNode_originalNode.EqualsIdentity(feature))
		{
			result = OriginalNode;
			return true;
		}

		if (StarLasuLanguage.Instance.PlaceholderNode_type.EqualsIdentity(feature))
		{
			result = Type;
			return true;
		}

		return false;
	}

	protected override bool TryGetPropertyRaw(Property feature, out object? result)
	{
		if (base.TryGetPropertyRaw(feature, out result))
			return true;
		if (StarLasuLanguage.Instance.PlaceholderNode_message.EqualsIdentity(feature))
		{
			result = _message;
			return true;
		}

		if (StarLasuLanguage.Instance.PlaceholderNode_type.EqualsIdentity(feature))
		{
			result = _type;
			return true;
		}

		return false;
	}

	protected override bool TryGetReferenceRaw(Reference feature, out IReferenceTarget? result)
	{
		if (base.TryGetReferenceRaw(feature, out result))
			return true;
		if (StarLasuLanguage.Instance.PlaceholderNode_originalNode.EqualsIdentity(feature))
		{
			result = _originalNode;
			return true;
		}

		return false;
	}

	/// <inheritdoc/>
        protected override bool SetInternal(Feature? feature, object? value)
	{
		if (base.SetInternal(feature, value))
			return true;
		if (StarLasuLanguage.Instance.PlaceholderNode_message.EqualsIdentity(feature))
		{
			if (value is string v)
			{
				SetMessage(v);
				return true;
			}

			throw new InvalidValueException(feature, value);
		}

		if (StarLasuLanguage.Instance.PlaceholderNode_originalNode.EqualsIdentity(feature))
		{
			if (value is null or com.strumenta.starlasu.ASTNode)
			{
				SetOriginalNode((com.strumenta.starlasu.ASTNode?)value);
				return true;
			}

			if (value is ReferenceTarget target)
			{
				SetOriginalNode(target);
				return true;
			}

			throw new InvalidValueException(feature, value);
		}

		if (StarLasuLanguage.Instance.PlaceholderNode_type.EqualsIdentity(feature))
		{
			if (value is com.strumenta.starlasu.PlaceholderNodeType v)
			{
				SetType(v);
				return true;
			}

			throw new InvalidValueException(feature, value);
		}

		return false;
	}

	protected override bool SetPropertyRaw(Property feature, object? value)
	{
		if (base.SetPropertyRaw(feature, value))
			return true;
		if (StarLasuLanguage.Instance.PlaceholderNode_message.EqualsIdentity(feature) && value is null or string)
			return SetMessageRaw((string?)value);
		if (StarLasuLanguage.Instance.PlaceholderNode_type.EqualsIdentity(feature) && value is null or com.strumenta.starlasu.PlaceholderNodeType)
			return SetTypeRaw((com.strumenta.starlasu.PlaceholderNodeType?)value);
		return false;
	}

	protected override bool SetReferenceRaw(Reference feature, ReferenceTarget? value)
	{
		if (base.SetReferenceRaw(feature, value))
			return true;
		if (StarLasuLanguage.Instance.PlaceholderNode_originalNode.EqualsIdentity(feature))
			return SetOriginalNodeRaw(value);
		return false;
	}

	/// <inheritdoc/>
        public override IEnumerable<Feature> CollectAllSetFeatures()
	{
		List<Feature> result = base.CollectAllSetFeatures().ToList();
		if (TryGetMessage(out _))
			result.Add(StarLasuLanguage.Instance.PlaceholderNode_message);
		if (TryGetOriginalNode(out _))
			result.Add(StarLasuLanguage.Instance.PlaceholderNode_originalNode);
		if (TryGetType(out _))
			result.Add(StarLasuLanguage.Instance.PlaceholderNode_type);
		return result;
	}
}

[LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "com_strumenta_starlasu-Statement-key")]
public partial interface Statement : CommonElement
{
}

[LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "com_strumenta_starlasu-TypeAnnotation-key")]
public partial interface TypeAnnotation : CommonElement
{
}

[LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "IssueSeverity")]
public enum IssueSeverity
{
	[LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "IssueSeverity-ERROR")]
	ERROR,
	[LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "IssueSeverity-INFO")]
	INFO,
	[LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "IssueSeverity-WARNING")]
	WARNING
}

[LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "IssueType")]
public enum IssueType
{
	[LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "IssueType-LEXICAL")]
	LEXICAL,
	[LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "IssueType-SEMANTIC")]
	SEMANTIC,
	[LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "IssueType-SYNTACTIC")]
	SYNTACTIC,
	[LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "IssueType-TRANSLATION")]
	TRANSLATION
}

[LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "com_strumenta_starlasu-PlaceholderNode-PlaceholderNodeType-key")]
public enum PlaceholderNodeType
{
	[LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "com-strumenta-StarLasu-PlaceholderNode-PlaceholderNodeType-id-FailingASTTransformation-key")]
	FailingASTTransformation,
	[LionCoreMetaPointer(Language = typeof(StarLasuLanguage), Key = "com-strumenta-StarLasu-PlaceholderNode-PlaceholderNodeType-id-MissingASTTransformation-key")]
	MissingASTTransformation
}